[tool.poetry]
name = "fastinni"
version = "0.1.0"
description = ""
authors = ["Michael Piccirillo <70709374+Khrysys@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
alembic = "^1.12.0"
asyncpg = "^0.28.0"
fastapi = "^0.95.1"
python-dotenv = "^1.0.0"
SQLAlchemy = "^2.0.20"
uvicorn = {extras = ["all"], version = "^0.23.2"}
fastapi-csrf-protect = "^0.3.2"
pyjwt = {extras = ["crypto"], version = "^2.8.0"}

[tool.poetry.group.dev.dependencies]
pyOpenSSL = "^23.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
