[tool.poetry]
name = "fastinni"
version = "0.1.0"
description = ""
authors = ["Michael Piccirillo <70709374+Khrysys@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.95.1"
python-dotenv = "^1.0.0"
uvicorn = {extras = ["all"], version = "^0.23.2"}
pyjwt = {extras = ["crypto"], version = "^2.8.0"}
fastapi-mail = "1.3.1"
sqlmodel = "^0.0.8"
psycopg2 = "^2.9.7"
humanize = "^4.8.0"
oauthlib = "^3.2.2"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
pyOpenSSL = "^23.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
